University Policy Knowledge Based System

1. Debate Arguments

In [4]:
debate <- data.frame(
  Argument_ID = c("A001","A002","A003","A004","A005","A006"),
  Position = c("For","For","For","Against","Against","Against"),
  Topic = c("Learning","Productivity","AI Literacy",
            "Academic Integrity","Dependency","Assessment"),
  Claim = c(
    "AI can provide students with immediate learning support.",
    "AI can help student complete routine academic tasks more efficiently.",
    "Allowing AI use can helps students develop AI literacy.",
    "Undisclosed AI-generated work may create academic integrity concerns.",
    "Excessive AI use may reduce students' independent problem-solving practice.",
    "AI use may make it more difficult to determine whether submitted work reflects student learning."
  )
)

debate

  Argument_ID Position Topic
1 A001        For      Learning
2 A002        For      Productivity
3 A003        For      AI Literacy
4 A004        Against  Academic Integrity
5 A005        Against  Dependency
6 A006        Against  Assessment
  Claim
1 AI can provide students with immediate learning support.
2 AI can help student complete routine academic tasks more efficiently.
3 Allowing AI use can helps students develop AI literacy.
4 Undisclosed AI-generated work may create academic integrity concerns.
5 Excessive AI use may reduce students' independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.

2. Evidence

In [7]:
evidence <- data.frame(
  Evidence_ID = c("E001", "E002", "E003", "E004", "E005", "E006"),
  Argument_ID = c("A001", "A002", "A003", "A004", "A005", "A006"),
  Evidence_Type = c("Research", "Research", "Policy", "Policy", "Research", "Research"),
  Strength = c("Strong", "Moderate", "Strong", "Strong", "Moderate", "Strong")
)

evidence

  Evidence_ID Argument_ID Evidence_Type Strength
1 E001        A001        Research      Strong
2 E002        A002        Research      Moderate
3 E003        A003        Policy        Strong
4 E004        A004        Policy        Strong
5 E005        A005        Research      Moderate
6 E006        A006        Research      Strong

3. Count the Arguments

In [9]:
table(debate$Position)

Against     For
      3       3

In [10]:
table(evidence$Strength)

Moderate   Strong
       2        4

In [11]:
nrow(debate)

[1] 6

4. Retrieve the Arguments

In [12]:
for_debate <- subset (
  debate,
  Position == "For"
)
print(for_debate)

  Argument_ID Position        Topic
1        A001      For     Learning
2        A002      For Productivity
3        A003      For  AI Literacy
                                                                  Claim
1              AI can provide students with immediate learning support.
2 AI can help student complete routine academic tasks more efficiently.
3               Allowing AI use can helps students develop AI literacy.

In [13]:
against_debate <- subset(
  debate,
  Position == "Against"
)

print (against_debate)

  Argument_ID Position              Topic
4        A004  Against Academic Integrity
5        A005  Against         Dependency
6        A006  Against         Assessment
                                                                                             Claim
4                            Undisclosed AI-generated work may create academic integrity concerns.
5                      Excessive AI use may reduce students' independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.

5. Connect the Arguments and Evidence

In [14]:
knowledge_base <- merge (
  debate,
  evidence,
  by = "Argument_ID"
)

print(knowledge_base)

  Argument_ID Position              Topic
1        A001      For           Learning
2        A002      For       Productivity
3        A003      For        AI Literacy
4        A004  Against Academic Integrity
5        A005  Against         Dependency
6        A006  Against         Assessment
                                                                                             Claim
1                                         AI can provide students with immediate learning support.
2                            AI can help student complete routine academic tasks more efficiently.
3                                          Allowing AI use can helps students develop AI literacy.
4                            Undisclosed AI-generated work may create academic integrity concerns.
5                      Excessive AI use may reduce students' independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.
  Evidence_ID Evidence_Type Strength
1        E001      Research   Strong
2        E002      Research Moderate
3        E003        Policy   Strong
4        E004        Policy   Strong
5        E005      Research Moderate
6        E006      Research   Strong

6. Convert Evidence Strength to Score

In [18]:
get_score <- function(Strength)(
  if (Strength == "Strong"){
    return(3)
  }else if (Strength == "Moderate"){
    return(2)
  }else if (Strength == "Weak"){
    return(1)
  }else {
    return(0)
  }
)

get_score("Strong")

[1] 3

7. Add Evidence Score

In [22]:
knowledge_base$Score <- mapply(
  get_score,
  knowledge_base$Strength
)

knowledge_base

  Argument_ID Position Topic
1 A001        For      Learning
2 A002        For      Productivity
3 A003        For      AI Literacy
4 A004        Against  Academic Integrity
5 A005        Against  Dependency
6 A006        Against  Assessment
  Claim
1 AI can provide students with immediate learning support.
2 AI can help student complete routine academic tasks more efficiently.
3 Allowing AI use can helps students develop AI literacy.
4 Undisclosed AI-generated work may create academic integrity concerns.
5 Excessive AI use may reduce students' independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.
  Evidence_ID Evidence_Type Strength Score
1 E001        Research      Strong   3
2 E002        Research      Moderate 2
3 E003        Policy        Strong   3
4 E004        Policy        Strong   3
5 E005        Research      Moderate 2
6 E006        Research      Strong   3

8. Classify Evidence Support

In [26]:
classify_support <- function(Score)(
  if (Score == 3){
    return("Strongly Supported")
  }else if (Score == 2){
    return("Moderately Supported")
  }else if (Score == 1){
    return("Weakly Supported")
  }else {
    return("Not Supported")
  }
)
classify_support(3)

[1] "Strongly Supported"

In [28]:
knowledge_base$Support_Level <- mapply(
  classify_support,
  knowledge_base$Score
)

print(knowledge_base)

  Argument_ID Position              Topic
1        A001      For           Learning
2        A002      For       Productivity
3        A003      For        AI Literacy
4        A004  Against Academic Integrity
5        A005  Against         Dependency
6        A006  Against         Assessment
                                                                                             Claim
1                                         AI can provide students with immediate learning support.
2                            AI can help student complete routine academic tasks more efficiently.
3                                          Allowing AI use can helps students develop AI literacy.
4                            Undisclosed AI-generated work may create academic integrity concerns.
5                      Excessive AI use may reduce students' independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.
  Evidence_ID Evidence_Type Strength Score        Support_Level
1        E001      Research   Strong     3   Strongly Supported
2        E002      Research Moderate     2 Moderately Supported
3        E003        Policy   Strong     3   Strongly Supported
4        E004        Policy   Strong     3   Strongly Supported
5        E005      Research Moderate     2 Moderately Supported
6        E006      Research   Strong     3   Strongly Supported

9. Search by Topic

In [33]:
search_topic <- function(topic){
  result <- subset (
    knowledge_base,
    Topic == topic
  )

  if(nrow(result) == 0) {
    cat("Topic not found.\n")
  }else {
    print(result)
  }
}

In [34]:
search_topic("Productivity")

  Argument_ID Position        Topic
2        A002      For Productivity
                                                                  Claim
2 AI can help student complete routine academic tasks more efficiently.
  Evidence_ID Evidence_Type Strength Score        Support_Level
2        E002      Research Moderate     2 Moderately Supported